pipeline {
    agent {
        docker {image 'node:12.22.9-alpine'}
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
                sh 'echo $USER'
                sh 'whoami' 
                dir('jenkins-light-auto'){  
                    sh 'npm install'
                    sh 'npm test'
                }               
               
                
                
                
                
            }
        }
    }
}