pipeline {
    agent any
    stages {
        stage('Preparing node environment') {
            steps {
                sh '''
                set +ex
                export NVM_DIR="$HOME/.nvm"
                . ~/.nvm/nvm.sh
                . ~/.profile
                . ~/.bashrc
                nvm use v18.16.1
                set -ex
                '''
            }
           
        }
        stage('Test') {
            steps {
                sh 'nvm --version'
                sh 'node --version'
                sh 'echo $USER'
                sh 'whoami' 
                dir('jenkins-light-auto'){  
                    sh 'npm install'
                    sh 'npm test'
                }               
               
                
                
                
                
            }
        }
    }
}